### ISSUE TITLE
Skript with container

### ISSUE THREAD

**Issue by Aushilfsarnie** [Vallek/firefox-cycle-scroll-tabs#1]
Hi! Thanks for the great script that worked for me for years too. Since a few days I use the extension Temporary Containers, which makes the script go crazy. Scrolling back works fine, but when you want to scroll forward it doesn't jump to the next tab, it always jumps to the first tab. How do I get the script working again? I think the class was changed from .tabbrowser-tab to identity-color-toolbar tabbrowser-tab. Maybe this helps...Thanks in advance

**Comment by Vallek** [comment]
Hi! You are welcome! Didn't think anyone use it) Frankly I don't use it myself because it's to much of a hassle to update unbranded firefox.

You don't need extension for containers. They built it. Search for "container tabs" in settings. 

Anyway I can't do anything about other extensions. But I checked my script now on last unbranded which is 97.0.1 (it also says nightly) and it works. So it's not classes. Hope that helps. Sorry if not)

**Comment by Aushilfsarnie** [comment]
Hello Vallek,
thank you very much for the quick feedback. I have since solved the problem myself. In case it also affects others: 
There is the nextClass to be added in line 31. E.g. if (nextClass != 'tabbrowser-tab identity-color-toolbar' && nextClass != 'identity-color-toolbar tabbrowser-tab')
Best regards
